apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
      - name: jenkins-docker-certs
        emptyDir: {}
      - name: jenkins-data
        emptyDir: {}
      containers:
      - name: docker
        image: docker:dind
        command: ["--storage-driver", "overlay2"]
        securityContext:
          privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: "/certs"
        volumeMounts:
        - name: jenkins-docker-certs
          mountPath: /certs/client
        - name: jenkins-data
          mountPath: /var/jenkins_home
        ports:
        - containerPort: 2376
      - name: jenkins-blueocean
        image: ereshkigal/jenkins-dind 
        env:
        - name: DOCKER_HOST
          value: "tcp://localhost:2376"
        - name: DOCKER_CERT_PATH
          value: "/certs/client"
        - name: DOCKER_TLS_VERIFY
          value: "1"
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        - name: jenkins-docker-certs
          mountPath: /certs/client
          readOnly: true
