apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  db-username: <base64-encoded-username>
  db-password: <base64-encoded-password>
  db-url: <base64-encoded-url>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOGGING_LEVEL: DEBUG
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-boot-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  labels:
    app: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot
        image: ereshkigal/pocjava-test-docker-image:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-url
        - name: LOGGING_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOGGING_LEVEL
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/spring-boot
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: spring-boot-logs-pvc
---
